name: Compile Examples
on: [push, pull_request]
jobs:
 build:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       fqbn: [
         "arduino:samd:mkr1000",
         "arduino:megaavr:uno2018:mode=on"
       ]

   steps:
     - uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - uses: arduino/actions/libraries/compile-examples@master
       with:
         fqbn: ${{ matrix.fqbn }}
